//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brands
    {
        public Brands()
        {
            this.BrandUsedNames = new HashSet<BrandUsedNames>();
            this.Products = new HashSet<Products>();
            this.SalesBrandCities = new HashSet<SalesBrandCities>();
            this.SalesBrandInstitutions = new HashSet<SalesBrandInstitutions>();
            this.Doctors = new HashSet<Doctors>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<BrandUsedNames> BrandUsedNames { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<SalesBrandCities> SalesBrandCities { get; set; }
        public virtual ICollection<SalesBrandInstitutions> SalesBrandInstitutions { get; set; }
        public virtual ICollection<Doctors> Doctors { get; set; }
    }
}
