//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public Cities()
        {
            this.Counties = new HashSet<Counties>();
            this.Distributors = new HashSet<Distributors>();
            this.Institutions = new HashSet<Institutions>();
            this.SalesBrandCities = new HashSet<SalesBrandCities>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.Guid> Province_Id { get; set; }
        public Nullable<System.Guid> CityLevel_Id { get; set; }
    
        public virtual CityLevels CityLevels { get; set; }
        public virtual Provinces Provinces { get; set; }
        public virtual ICollection<Counties> Counties { get; set; }
        public virtual ICollection<Distributors> Distributors { get; set; }
        public virtual ICollection<Institutions> Institutions { get; set; }
        public virtual ICollection<SalesBrandCities> SalesBrandCities { get; set; }
    }
}
