//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributors
    {
        public Distributors()
        {
            this.DistributorProductLinks = new HashSet<DistributorProductLinks>();
            this.DistributorUsedNames = new HashSet<DistributorUsedNames>();
            this.InstitutionUsedNames = new HashSet<InstitutionUsedNames>();
            this.OpentingStocks = new HashSet<OpentingStocks>();
            this.SalesFlows = new HashSet<SalesFlows>();
            this.SalesFlows1 = new HashSet<SalesFlows>();
            this.SalesFlowsFiles = new HashSet<SalesFlowsFiles>();
            this.SalesPositions = new HashSet<SalesPositions>();
            this.Employees = new HashSet<Employees>();
            this.Products = new HashSet<Products>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string TelNum { get; set; }
        public string Address { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string Code { get; set; }
        public string OldDistributorId { get; set; }
        public string OldInsId { get; set; }
        public bool HasTemplate { get; set; }
        public int Frequency { get; set; }
        public Nullable<System.DateTime> SingleStraTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.Guid> City_Id { get; set; }
        public Nullable<System.Guid> Type_Id { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual ICollection<DistributorProductLinks> DistributorProductLinks { get; set; }
        public virtual DistributorTypes DistributorTypes { get; set; }
        public virtual ICollection<DistributorUsedNames> DistributorUsedNames { get; set; }
        public virtual ICollection<InstitutionUsedNames> InstitutionUsedNames { get; set; }
        public virtual ICollection<OpentingStocks> OpentingStocks { get; set; }
        public virtual ICollection<SalesFlows> SalesFlows { get; set; }
        public virtual ICollection<SalesFlows> SalesFlows1 { get; set; }
        public virtual ICollection<SalesFlowsFiles> SalesFlowsFiles { get; set; }
        public virtual ICollection<SalesPositions> SalesPositions { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
