//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public Doctors()
        {
            this.Brands = new HashSet<Brands>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Major { get; set; }
        public bool IsInternationalStudent { get; set; }
        public string Specialty { get; set; }
        public bool IsValid { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> AdministrativePost_Id { get; set; }
        public Nullable<System.Guid> Institution_Id { get; set; }
        public Nullable<System.Guid> Degree_Id { get; set; }
        public Nullable<System.Guid> HospitalSection_Id { get; set; }
        public Nullable<System.Guid> ModifyByEmployee_Id { get; set; }
        public Nullable<System.Guid> ProfessionalCategory_Id { get; set; }
        public Nullable<System.Guid> Qualification_Id { get; set; }
        public Nullable<System.Guid> TechnicalPost_Id { get; set; }
    
        public virtual AdministrativePosts AdministrativePosts { get; set; }
        public virtual Degrees Degrees { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual HospitalSections HospitalSections { get; set; }
        public virtual Institutions Institutions { get; set; }
        public virtual ProfessionalCategories ProfessionalCategories { get; set; }
        public virtual Qualifications Qualifications { get; set; }
        public virtual TechnicalPosts TechnicalPosts { get; set; }
        public virtual ICollection<Brands> Brands { get; set; }
    }
}
