//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalSections
    {
        public HospitalSections()
        {
            this.Doctors = new HashSet<Doctors>();
            this.HospitalSections1 = new HashSet<HospitalSections>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentHospitalSection_Id { get; set; }
    
        public virtual ICollection<Doctors> Doctors { get; set; }
        public virtual ICollection<HospitalSections> HospitalSections1 { get; set; }
        public virtual HospitalSections HospitalSections2 { get; set; }
    }
}
