//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institutions
    {
        public Institutions()
        {
            this.Doctors = new HashSet<Doctors>();
            this.FocusHospitals = new HashSet<FocusHospitals>();
            this.InstitutionUsedNames = new HashSet<InstitutionUsedNames>();
            this.SalesBrandInstitutions = new HashSet<SalesBrandInstitutions>();
            this.SalesFlows = new HashSet<SalesFlows>();
            this.SalesPositions = new HashSet<SalesPositions>();
            this.VirtualInstitutions = new HashSet<VirtualInstitutions>();
            this.VirtualInstitutions1 = new HashSet<VirtualInstitutions>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Address { get; set; }
        public string TelNum { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.Guid> City_Id { get; set; }
        public Nullable<System.Guid> County_Id { get; set; }
        public Nullable<System.Guid> Level_Id { get; set; }
        public Nullable<System.Guid> Province_Id { get; set; }
        public Nullable<System.Guid> Tier_Id { get; set; }
        public Nullable<System.Guid> Type_Id { get; set; }
        public string ShortName { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Counties Counties { get; set; }
        public virtual ICollection<Doctors> Doctors { get; set; }
        public virtual ICollection<FocusHospitals> FocusHospitals { get; set; }
        public virtual InstitutionLevels InstitutionLevels { get; set; }
        public virtual InstitutionTiers InstitutionTiers { get; set; }
        public virtual InstitutionTypes InstitutionTypes { get; set; }
        public virtual Provinces Provinces { get; set; }
        public virtual ICollection<InstitutionUsedNames> InstitutionUsedNames { get; set; }
        public virtual ICollection<SalesBrandInstitutions> SalesBrandInstitutions { get; set; }
        public virtual ICollection<SalesFlows> SalesFlows { get; set; }
        public virtual ICollection<SalesPositions> SalesPositions { get; set; }
        public virtual ICollection<VirtualInstitutions> VirtualInstitutions { get; set; }
        public virtual ICollection<VirtualInstitutions> VirtualInstitutions1 { get; set; }
    }
}
