//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeftNavigations
    {
        public LeftNavigations()
        {
            this.LeftNavigations1 = new HashSet<LeftNavigations>();
            this.Employees = new HashSet<Employees>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public Nullable<System.Guid> Parent_Id { get; set; }
    
        public virtual ICollection<LeftNavigations> LeftNavigations1 { get; set; }
        public virtual LeftNavigations LeftNavigations2 { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
