//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Batches = new HashSet<Batches>();
            this.DistributorProductLinks = new HashSet<DistributorProductLinks>();
            this.FocusHospitals = new HashSet<FocusHospitals>();
            this.MarketingSalesTargets = new HashSet<MarketingSalesTargets>();
            this.OpentingStocks = new HashSet<OpentingStocks>();
            this.ProductUsedNames = new HashSet<ProductUsedNames>();
            this.SalesFlows = new HashSet<SalesFlows>();
            this.SalesPositions = new HashSet<SalesPositions>();
            this.Distributors = new HashSet<Distributors>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> Brand_Id { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
    
        public virtual ICollection<Batches> Batches { get; set; }
        public virtual Brands Brands { get; set; }
        public virtual ICollection<DistributorProductLinks> DistributorProductLinks { get; set; }
        public virtual ICollection<FocusHospitals> FocusHospitals { get; set; }
        public virtual ICollection<MarketingSalesTargets> MarketingSalesTargets { get; set; }
        public virtual ICollection<OpentingStocks> OpentingStocks { get; set; }
        public virtual ICollection<ProductUsedNames> ProductUsedNames { get; set; }
        public virtual ICollection<SalesFlows> SalesFlows { get; set; }
        public virtual ICollection<SalesPositions> SalesPositions { get; set; }
        public virtual ICollection<Distributors> Distributors { get; set; }
    }
}
