//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provinces
    {
        public Provinces()
        {
            this.Cities = new HashSet<Cities>();
            this.EmployeeProvinces = new HashSet<EmployeeProvinces>();
            this.Institutions = new HashSet<Institutions>();
            this.MarketingSalesTargets = new HashSet<MarketingSalesTargets>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }
        public string PostCode { get; set; }
    
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual ICollection<EmployeeProvinces> EmployeeProvinces { get; set; }
        public virtual ICollection<Institutions> Institutions { get; set; }
        public virtual ICollection<MarketingSalesTargets> MarketingSalesTargets { get; set; }
    }
}
