//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesFlows
    {
        public System.Guid Id { get; set; }
        public string BatchCode { get; set; }
        public decimal Qty { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> SoldPrice { get; set; }
        public string DistributorName { get; set; }
        public Nullable<System.Guid> ToDistributorId { get; set; }
        public Nullable<System.Guid> ToInstitutionId { get; set; }
        public string LowerName { get; set; }
        public bool Invalid { get; set; }
        public bool SalesAreaVerify { get; set; }
        public bool BacthCodeVerify { get; set; }
        public System.DateTime SalesDate { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> Batches_Id { get; set; }
        public Nullable<System.Guid> FromDistributor_Id { get; set; }
        public Nullable<System.Guid> SalesFlowsFile_Id { get; set; }
        public Nullable<System.Guid> Employee_Id { get; set; }
        public Nullable<System.Guid> Product_Id { get; set; }
        public Nullable<System.Guid> SalesRevision_Id { get; set; }
    
        public virtual Batches Batches { get; set; }
        public virtual Distributors Distributors { get; set; }
        public virtual Distributors Distributors1 { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Institutions Institutions { get; set; }
        public virtual Products Products { get; set; }
        public virtual SalesFlowsFiles SalesFlowsFiles { get; set; }
        public virtual SalesRevisions SalesRevisions { get; set; }
    }
}
