//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesFlowsFiles
    {
        public SalesFlowsFiles()
        {
            this.SalesFlowReviews = new HashSet<SalesFlowReviews>();
            this.SalesFlows = new HashSet<SalesFlows>();
            this.Comments = new HashSet<Comments>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string LocalFileName { get; set; }
        public string Name { get; set; }
        public int SalesFlowFileType { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime ReportMonth { get; set; }
        public Nullable<System.Guid> Distributor_Id { get; set; }
        public Nullable<System.Guid> Employee_Id { get; set; }
    
        public virtual Distributors Distributors { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ICollection<SalesFlowReviews> SalesFlowReviews { get; set; }
        public virtual ICollection<SalesFlows> SalesFlows { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
