//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace excelTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMCSFEEntities : DbContext
    {
        public SMCSFEEntities()
            : base("name=SMCSFEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdministrativePosts> AdministrativePosts { get; set; }
        public virtual DbSet<AgreementTypes> AgreementTypes { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Batches> Batches { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<BrandUsedNames> BrandUsedNames { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<CityLevels> CityLevels { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Counties> Counties { get; set; }
        public virtual DbSet<Degrees> Degrees { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DistributorProductLinks> DistributorProductLinks { get; set; }
        public virtual DbSet<Distributors> Distributors { get; set; }
        public virtual DbSet<DistributorTypes> DistributorTypes { get; set; }
        public virtual DbSet<DistributorUsedNames> DistributorUsedNames { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<EmployeeProvinces> EmployeeProvinces { get; set; }
        public virtual DbSet<EmployeeRoles> EmployeeRoles { get; set; }
        public virtual DbSet<EmployeeRolesEmployees> EmployeeRolesEmployees { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeeTerritories> EmployeeTerritories { get; set; }
        public virtual DbSet<FocusHospitals> FocusHospitals { get; set; }
        public virtual DbSet<FocusHospitalTypes> FocusHospitalTypes { get; set; }
        public virtual DbSet<HospitalSections> HospitalSections { get; set; }
        public virtual DbSet<InstitutionLevels> InstitutionLevels { get; set; }
        public virtual DbSet<Institutions> Institutions { get; set; }
        public virtual DbSet<InstitutionTiers> InstitutionTiers { get; set; }
        public virtual DbSet<InstitutionTypes> InstitutionTypes { get; set; }
        public virtual DbSet<InstitutionUsedNames> InstitutionUsedNames { get; set; }
        public virtual DbSet<LeftNavigations> LeftNavigations { get; set; }
        public virtual DbSet<MarketingSalesTargets> MarketingSalesTargets { get; set; }
        public virtual DbSet<OpentingStocks> OpentingStocks { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductUsedNames> ProductUsedNames { get; set; }
        public virtual DbSet<ProfessionalCategories> ProfessionalCategories { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<Qualifications> Qualifications { get; set; }
        public virtual DbSet<SalesBrandCities> SalesBrandCities { get; set; }
        public virtual DbSet<SalesBrandInstitutions> SalesBrandInstitutions { get; set; }
        public virtual DbSet<SalesFlowPermissionRules> SalesFlowPermissionRules { get; set; }
        public virtual DbSet<SalesFlowReviews> SalesFlowReviews { get; set; }
        public virtual DbSet<SalesFlows> SalesFlows { get; set; }
        public virtual DbSet<SalesFlowsFiles> SalesFlowsFiles { get; set; }
        public virtual DbSet<SalesPositions> SalesPositions { get; set; }
        public virtual DbSet<SalesRevisions> SalesRevisions { get; set; }
        public virtual DbSet<SalesTargets> SalesTargets { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalPosts> TechnicalPosts { get; set; }
        public virtual DbSet<Territories> Territories { get; set; }
        public virtual DbSet<TerritoryReportLines> TerritoryReportLines { get; set; }
        public virtual DbSet<TerritoryRoles> TerritoryRoles { get; set; }
        public virtual DbSet<TerritorySalesPositions> TerritorySalesPositions { get; set; }
        public virtual DbSet<VirtualInstitutions> VirtualInstitutions { get; set; }
    }
}
